name: khuchinque-framework

services:
  postgres:
    image: postgres:15
    container_name: khuchinque-framework-postgres
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: khuchinque-framework-ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_HOST: 0.0.0.0
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: khuchinque-framework-open-webui
    ports:
      - "3000:8080"
    environment:
      - WEBUI_SECRET_KEY=your-secret-key-here
      - WEBUI_JWT_SECRET_KEY=your-jwt-secret-here
    volumes:
      - ./data/webui:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: khuchinque-framework-n8n
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: "localhost"
      N8N_PORT: 5678
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
    volumes:
      - ./n8n-local-files:/home/node/.n8n
    depends_on:
      - postgres
    restart: unless-stopped

  browser-use:
    build:
      context: ./browser-n8n-local
    container_name: khuchinque-framework-browser-use
    ports:
      - "8000:8000"
    env_file:
      - ./browser-n8n-local/.env
    volumes:
      - ./browser-n8n-local:/app
    restart: unless-stopped

  mcpo:
    build:
      context: ./mcpo
    container_name: khuchinque-framework-mcpo
    ports:
      - "9000:9000"
    restart: unless-stopped
